name: Unzip uploaded ZIPs

on:
  push:
    paths:
      - 'webllm.zip'
      - 'tokenizer.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip tokenizer.zip
        if: ${{ github.event.head_commit.added && contains(github.event.head_commit.added, 'tokenizer.zip') }}
        run: unzip -o tokenizer.zip -d tokenizer

      - name: Unzip webllm.zip
        if: ${{ github.event.head_commit.added && contains(github.event.head_commit.added, 'webllm.zip') }}
        run: unzip -o webllm.zip -d webllm

      - name: Commit unzipped folders
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tokenizer webllm
          git commit -m "Unzipped folders from zips"
          git push
