name: Unzip uploaded ZIPs

on:
  push:
    branches:
      - main       # <-- set your default branch here
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip tokenizer.zip
        if: exists('tokenizer.zip')
        run: unzip -o tokenizer.zip -d tokenizer

      - name: Unzip webllm.zip
        if: exists('webllm.zip')
        run: unzip -o webllm.zip -d webllm

      - name: Push unzipped folders back
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tokenizer webllm
          git commit -m "Unzipped folders from .zip files"
          git push
