name: Unzip uploaded ZIPs

on:
  push:
    branches:
      - main
    paths:
      - '*.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List repo files
        run: ls -la

      - name: Find and unzip all zip files
        run: |
          for file in *.zip; do
            folder="${file%.zip}"
            echo "Unzipping $file to $folder/"
            unzip -o "$file" -d "$folder"
            ls -la "$folder"
          done

      - name: Commit unzipped folders if any changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          for file in *.zip; do
            folder="${file%.zip}"
            if [ -d "$folder" ]; then
              git add "$folder"
            fi
          done
          git diff --cached --quiet || (git commit -m "Unzipped folders from zip files" && git push)
